### ISSUE TITLE
Not downloading Patreon images

### ISSUE THREAD

**Issue by inusbaum** [fake-name/xA-Scraper#15] opened 2017-10-06 20:47 UTC
I see it combing through the posts, it complains that there are no attachments, but looking at the code it appears to be looking at the post image and adding to the files array. It has created the requisite directories, so I know it has access to the file system, and there are no errors (other than the no attachment warning) so I am not sure whats up. 

I am new to Python, but have 15 years of PHP experience and work daily in rails, I feel like I *should* be able to figure this out...

**Comment by inusbaum** [comment] 2017-10-06 21:03
Hah... fixed it... kind of

at line 245 and the subsequent save_image call you are using post_content when it should be post_info, since post_content["post_file"] doesn't exist it just skips the bit where it should be downloading the image... 

only problem is that now, the images are failing with 403s

**Comment by inusbaum** [comment] 2017-10-06 21:09
ah, you are urlencoding the already urlencoded string... no idea how to fix that, will likely comment again in a few minutes with a fix lol

**Comment by inusbaum** [comment] 2017-10-06 21:21
well, I didn;t actually fix it per se... but I solved the issue with this pone patreon.

Basically, one there is a url segment that contains %3D, which is getting translated somewhere into %253D. I fixed it for this one case with str.replace("%3D","=") and letting whatever is making the url safe do its thing.  

Thanks for making this tool though, it's pretty awesome

**Comment by fake-name** [comment] 2017-10-06 23:41
Hrm, yeah, the problem is I pushed down a lot of the URL complexity handling to the WebRequest class, and it's kind of dumb about double-encoding already-encoded content.

**Comment by inusbaum** [comment] 2017-10-07 00:00
Yeah, I figured it was something simple, but as I said I'm not a python
jockey.

The bigger issue is the post_content vs. post_info as it stops the code
from detecting the posts image at all

**Comment by fake-name** [comment] 2017-10-07 02:03
Ok, I'm not sure what's going on here, as as far as I can tell, the patreon scraper *does* fetch post images. 

It sounds like you might be using a slightly old version of the code, as the post_content/post_file thing, as well as the spurious encoding issue were fixed in https://github.com/fake-name/xA-Scraper/commit/4ab1074766f368facb9e5b3dccdd2f1be4e5b541 last week.

**Closed by fake-name** 2017-10-07 02:03 UTC
